# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/yuyi-yutie"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/3546602811689251?spm_id_from=333.1007.0.0"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "zhihu"
name = "Zhihu"
url = "https://www.zhihu.com/people/89-70-59-86-39"

[social.params]
icon = "brand-zhihu"